# Problem 1 

In [1]:

import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)


print(np.sort(arr))


[1 2 3 4 5]
[1 2 3 4 5]


# Problem 2

In [5]:
arr = np.array([10,15,30,45,60])
print(arr)



arr = np.arange(5,15)
print(arr)


arr = np.arange(50,100,5)
print(arr)



arr = np.zeros(10)
print(arr)



arr = np.ones(10)
print(arr)



arr = np.linspace(0,100,5)
print(arr)



arr = np.random.randint(10,30,5)
print(arr)



arr = np.random.uniform(-1,1,10)
print(arr)



arr = np.random.randint(10,50,15).reshape(3,5)
print(arr)



print(arr.sum(axis=1))
print(arr.sum(axis=0))



print(arr.max())
print(arr.min())
print(arr.mean())



print(arr.argmax())



arr1 = np.arange(10,20)
print(arr1[:3])



print(arr[::-1])



print(arr[0])



print(arr[2,3]) 



print(arr[:,0])


print(arr**2)



arr = np.random.randint(-50,50,100)
print(arr[(arr>0) & (arr%2==0)])

[10 15 30 45 60]
[ 5  6  7  8  9 10 11 12 13 14]
[50 55 60 65 70 75 80 85 90 95]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[  0.  25.  50.  75. 100.]
[21 23 29 10 15]
[ 0.49314707  0.65254907 -0.17305295 -0.20888815  0.59692039 -0.10140402
 -0.16673494 -0.59652822 -0.44997699  0.60574957]
[[22 30 27 27 27]
 [45 28 36 16 11]
 [40 40 39 17 11]]
[133 136 147]
[107  98 102  60  49]
45
11
27.733333333333334
5
[10 11 12]
[[40 40 39 17 11]
 [45 28 36 16 11]
 [22 30 27 27 27]]
[22 30 27 27 27]
17
[22 45 40]
[[ 484  900  729  729  729]
 [2025  784 1296  256  121]
 [1600 1600 1521  289  121]]
[32 18 18 38  8 16  2  8 28 40 16 18 16 44 26 18 46  4 28 10 38 18 38 42
 24]
