# Problem 1

In [3]:


import numpy as np

matris = np.random.randint(0, 11, 5)
print(matris)

print( matris.shape)

yeni_matris = matris.reshape(1, 5)
print(yeni_matris)

print(yeni_matris.ndim)



[3 9 5 7 9]
(5,)
[[3 9 5 7 9]]
2


# Problem 2

In [4]:

import numpy as np
matris = np.random.choice([1, 3, 5, 7, 9], size=(2, 3))
print(matris)

parca1 = matris[:, :2]
parca2 = matris[:, 2:]
print(parca1)
print(parca2)

birlesmis_matris = np.concatenate((parca1, parca2), axis=1)
print(birlesmis_matris)






[[1 7 9]
 [3 5 5]]
[[1 7]
 [3 5]]
[[9]
 [5]]
[[1 7 9]
 [3 5 5]]


# Problem 3

In [6]:

matris = np.random.randint(5, 101, size=(2, 5))
print(matris)


matris.shape
matris.ndim
matris.size


[[24 93 56 39 79]
 [81  7 55 77 72]]


10